apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appsproject
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: default Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  sourceNamespaces:
  - default
  - argocd
  destinations:
  - server: https://kubernetes.default.svc
    namespace: default

  # Cluster resource whitelist
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'