apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
    log.level: debug
    applications_api: argocd
    # The address of Argo CD API endpoint - defaults to argocd-server.argocd
    argocd.server_addr: argocd-server.argocd
    # Whether to ignore invalid TLS cert from Argo CD API endpoint
    argocd.insecure: "true"
    # Whether to use plain text connection (http) instead of TLS (https)
    argocd.plaintext: "false"
    registries.conf: |
      registries:
      - name: ECR
        prefix: 342273264631.dkr.ecr.eu-central-1.amazonaws.com
        api_url: https://342273264631.dkr.ecr.eu-central-1.amazonaws.com
        ping: yes
        insecure: no
        credentials: ext:/scripts/ecr-login.sh
        credsexpire: 11h
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-authscripts
data:
  {{- toYaml .Values.authScripts.scripts | nindent 2}}