apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: {{ .Values.myapp.image }}
    argocd.argoproj.io/image-updater.update-policy: >
      myapp.image=semver:*,{{ .Values.myapp.image }}
  name: myapp
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://brutalhex.github.io/OpsWork
    targetRevision: HEAD
    chart: myapp
    helm:
      valueFiles:
        - values.yaml
      releaseName: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true