apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: {{ .Values.myapp.image }}
    argocd.argoproj.io/image-updater.update-policy: >
      myapp.image=semver:*,{{ .Values.myapp.image }}
  name: myapp
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: appsproject
  source:
    repoURL: https://brutalhex.github.io/OpsWork
    targetRevision: 0.2.20 
    chart: myapp
    helm:
      valueFiles:
        - values.yaml
      releaseName: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      #- CreateNamespace=true
      - Replace=true
    retry:
      limit: 5  
      backoff:
        duration: 10s  
        factor: 2  
        maxDuration: 3m