apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo:^0.1
    argocd.argoproj.io/image-updater.update-policy: >
      myapp.image=semver:*,{{ .Values.myapp.image }}
  name: myapp
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: git@github.com/BrutalHex/OpsWork.git
    
    targetRevision: HEAD
    chart: myapp
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true