apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:BrutalHex
  type: git
  sshPrivateKey: |
    {{ .Values.privatekey }}
  insecure: "true" # Do not perform a host key check for the server. Defaults to "false"
  enableLfs: "true"
