apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: main-vservice
  namespace: default
spec:
  hosts:
  - '*'
  gateways:
  - istio-system/main-gateway
  http:
  - route:
    - destination:
        host: myapp.default.svc.cluster.local
        port:
          number: 80
 
