apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: main-vservice
  namespace: istio-system
spec:
  hosts:
  - '*'
  gateways:
  - main-gateway
  http:
  - match:
    route:
    - destination:
        host: myapp.default.svc.cluster.local
        port:
          number: 80