apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port | int }}
    targetPort: {{ .Values.service.internalPort | int }}
    protocol: TCP
    name: "{{ .Values.service.internalPort }}-main"
  selector: 
    app: {{ .Release.Name }}

 