name: Terraform
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.6

 
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'


    - name: Run Python script
      run: |
        python setup_cluster.py

    
  
    - name: Save output as GitHub secret
      id: save_secret
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        OUTPUT_VALUE=$(terraform output -raw output_name)
        echo "OUTPUT_VALUE=$OUTPUT_VALUE" >> $GITHUB_ENV

        curl -X PUT \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          --data "{\"key\": \"YOUR_SECRET_NAME\", \"encrypted_value\": \"$(echo -n $OUTPUT_VALUE | base64)\", \"visibility\": \"private\"}" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets

